name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test 🧪
        run: |
          npm ci
          npm run check-ci
